### ISSUE TITLE
relay_read()/relay_write() use buffer of size 8 instead of 64K

### ISSUE THREAD

**Issue by p-pautov** [cmello/draft-http-tunnel#1]
https://github.com/cmello/draft-http-tunnel/blob/7a1acd8d414ba8b460289ea1c47b434735a4da1a/src/HttpTunnel.h#L175
https://github.com/cmello/draft-http-tunnel/blob/7a1acd8d414ba8b460289ea1c47b434735a4da1a/src/HttpTunnel.h#L189

In above lines "sizeof(buffer)" returns the size of a pointer (8 on 64-bit system).

**Comment by cmello** [comment]
@p-pautov Thank you very much for reporting that bug! I'll fix it soon. Best regards!

**Comment by cmello** [comment]
Fixed. Again thank you very much @p-pautov !!
